### ISSUE TITLE
Error while communicating with the Moodle System!

### ISSUE THREAD

**Issue by steelstrings** [C0D3D3V/Moodle_Downloader_2#1]
```
python3 main.py --init
Do you want to activate Notifications via mail [y/n]?   n
Do you want to configure Error Reporting via Sentry? [y/n]n
[The following Credentials are not saved, it is only used temporarily to generate a login token.]
URL of Moodle:   https://moodle.bulme.at
Username for Moodle:   <username>
Password for Moodle [no output]:   
Error while communicating with the Moodle System! (An Unexpected Error happened on side of the Moodle System!) Please try again.
```

version (https://moodle.bulme.at/lib/upgrade.txt):

```
This files describes API changes in core libraries and APIs,
information provided here is intended especially for developers.

=== 3.7 ===
* Nodes in the navigation api can have labels for each group. See set/get_collectionlabel().
* The method core_user::is_real_user() now returns false for userid = 0 parameter
——— ~ *snip* ~ ———
```

---

**EDIT:** take a look at the title of the repo

**Comment by C0D3D3V** [comment]
Thank you for reporting this. 

The Error message just tells me, that the moodle system did not answer with a normal status code. Maybe this is because moodle.bulme.at also supports http but redirects to https. But generally it looks like your Moodle is supported. I just need to make an update, so that an redirect of the login request will get detected on configuration. 

I'll let you know when the update is ready.

**Comment by C0D3D3V** [comment]
Could you please check if the last changes have changed anything about the situation? Has the terminal output changed?
