### ISSUE TITLE
sso login

### ISSUE THREAD

**Issue by shoeper** [C0D3D3V/Moodle_Downloader_2#20]
For me the automated sso login does not work for one moodle. It does work for another moodle.

SSO url: `https://moodle.informatik.tu-darmstadt.de/admin/tool/mobile/launch.php?service=moodle_mobile_app&passport=12345&urlscheme=http%3A%2F%2Flocalhost`

`error/Invalid parameter: the value of urlscheme isn't valid. It should start with a letter and can only contain letters, numbers and the characters "." "+" "-".`

![Screenshot from 2020-03-24 13-42-35](https://user-images.githubusercontent.com/5340585/77426992-dc515200-6dd5-11ea-93e8-8dfc91308003.png)

It works for another moodle where the url is `https://moodle.tu-darmstadt.de/admin/tool/mobile/launch.php?service=moodle_mobile_app&passport=12345&urlscheme=http%3A%2F%2Flocalhost`

Didn't find the version of the moodles so far and from a quick search it looks like they're trying to hide it.

**Comment by C0D3D3V** [comment]
With your first moodle you should get a [warning](https://github.com/C0D3D3V/Moodle_Downloader_2/blob/34cc46f2ec317968c238ae8b30510ba7377a883f/moodle_connector/moodle_service.py#L87) in the terminal, because the source code of moodle has been adapted so that automatic copying is no longer possible, maybe this will change again in a newer version.

https://github.com/moodle/moodle/commit/12da324fc01d61293ed5920fe858310d51ad8414#diff-e718a28a7eeb19fa429d7f3e542992e5R38
Line 38 from  admin/tool/mobile/launch.php

This is the reason why I also offer the possibility to copy the Toke-Url manually.

**Comment by C0D3D3V** [comment]
The version of your first moodle is [3.8.2](https://moodle.informatik.tu-darmstadt.de/lib/upgrade.txt).
The version of the second moodle is [3.7.4](https://moodle.tu-darmstadt.de/lib/upgrade.txt)
