### ISSUE TITLE
command to download a specific course

### ISSUE THREAD

**Issue by sds100** [C0D3D3V/Moodle_Downloader_2#5]
have a command to download a course by its id.

**Comment by C0D3D3V** [comment]
You mean like a white list?
So that only the courses on that list are downloaded? Currently there is only a blacklist implemented.

In the issue #4 some ideas were mentioned that I still have to think about, so I have not implemented a whitelist yet. It is expected that soon it will be possible to define more precisely which courses should be downloaded (also that you can rename them ect.)

But if you want to try something on it, you are welcome to try to implement it yourself, you can use the blacklist for orientation.

**Comment by sds100** [comment]
Yeah, that's what I mean! I'll try having a go myself.
Thank you.
________________________________

**Comment by C0D3D3V** [comment]
Check out the new feature `python main.py --config`
If this meets your request, you can close the issue.

**Comment by C0D3D3V** [comment]
PS. You need to install the new requirement
`pip3 install -r requirements.txt`
